/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timesheet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Expense service. Represents a row in the &quot;Timesheet_Expense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timesheet.model.impl.ExpenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timesheet.model.impl.ExpenseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Expense
 * @see com.liferay.timesheet.model.impl.ExpenseImpl
 * @see com.liferay.timesheet.model.impl.ExpenseModelImpl
 * @generated
 */
public interface ExpenseModel extends BaseModel<Expense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expense model instance should use the {@link Expense} interface instead.
	 */

	/**
	 * Returns the primary key of this expense.
	 *
	 * @return the primary key of this expense
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expense.
	 *
	 * @param primaryKey the primary key of this expense
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the expense ID of this expense.
	 *
	 * @return the expense ID of this expense
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this expense.
	 *
	 * @param expenseId the expense ID of this expense
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the project ID of this expense.
	 *
	 * @return the project ID of this expense
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this expense.
	 *
	 * @param projectId the project ID of this expense
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the description of this expense.
	 *
	 * @return the description of this expense
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this expense.
	 *
	 * @param description the description of this expense
	 */
	public void setDescription(String description);

	/**
	 * Returns the purchased date of this expense.
	 *
	 * @return the purchased date of this expense
	 */
	public Date getPurchasedDate();

	/**
	 * Sets the purchased date of this expense.
	 *
	 * @param purchasedDate the purchased date of this expense
	 */
	public void setPurchasedDate(Date purchasedDate);

	/**
	 * Returns the type of this expense.
	 *
	 * @return the type of this expense
	 */
	public int getType();

	/**
	 * Sets the type of this expense.
	 *
	 * @param type the type of this expense
	 */
	public void setType(int type);

	/**
	 * Returns the value of this expense.
	 *
	 * @return the value of this expense
	 */
	public double getValue();

	/**
	 * Sets the value of this expense.
	 *
	 * @param value the value of this expense
	 */
	public void setValue(double value);

	/**
	 * Returns the file entry ID of this expense.
	 *
	 * @return the file entry ID of this expense
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this expense.
	 *
	 * @param fileEntryId the file entry ID of this expense
	 */
	public void setFileEntryId(long fileEntryId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Expense expense);

	public int hashCode();

	public CacheModel<Expense> toCacheModel();

	public Expense toEscapedModel();

	public String toString();

	public String toXmlString();
}